# application versions
# assets
version: "{{ collectory_version | default('LATEST') }}"
artifactId: "{{ collectory_app | default('') }}"
groupId: "au.org.ala"
# collectory does not need a value for classifier
classifier: ''
packaging: "war"

collectory_war_url: "{{maven_repo_ws_url}}"
