- include: ../../common/tasks/setfacts.yml

- name: ensure biocache directory exists
  file: path=/usr/lib/biocache state=directory

- name: clean biocache existing extract
  shell: "rm -Rf /usr/lib/biocache/lib /usr/lib/biocache/*.jar"
  ignore_errors: yes

- name: copy biocache logging config
  copy: src=lib/log4j.xml dest=/usr/lib/biocache/log4j.xml

- name: copy biocache logging config
  copy: src=config/subgroups.json dest={{data_dir}}/biocache/config/subgroups.json

- name: copy biocache store jar
  get_url: url={{biocache_store_url}} dest="/usr/lib/biocache/biocache.zip" force=no owner={{tomcat_user}} group={{tomcat_user}}

- name: install unzip (Debian only)
  apt: pkg=unzip state=present
  when: ansible_os_family == "Debian"

- name: unjar biocache
  shell: "unzip /usr/lib/biocache/biocache.zip -d /usr/lib/biocache/"

- name: create the templated biocache.sh
  template: src=biocache.sh dest=/usr/lib/biocache/biocache mode=777

- name: clean biocache existing extract
  shell: "mv /usr/lib/biocache/biocache-store-*.jar /usr/lib/biocache/biocache.jar"
  ignore_errors: yes  

- name: create biocache executable
  shell: "cat /usr/lib/biocache/biocache.jar >> /usr/lib/biocache/biocache"
  ignore_errors: yes  

- name: make the symlink for /usr/bin/biocache 
  file: src=/usr/lib/biocache/biocache dest=/usr/bin/biocache state=link

- name: create the reindex directory
  file: path={{item}} state=directory mode=777
  with_items:
    - "{{data_dir}}/biocache-reindex/solr-template"
    - "{{data_dir}}/biocache-reindex/solr-create"
    - "{{data_dir}}/biocache-reindex/solr"

- name: copy solr-template
  copy: src=solr-template dest={{data_dir}}/biocache-reindex/
