- include: ../../common/tasks/setfacts.yml

########## REDHAT ########## 

- name: setup yum repo
  copy: src=yum/datastax.repo dest=/etc/yum.repos.d/datastax.repo
  when: ansible_os_family == "RedHat"   

# Note: Ansible 1.6.x yum does not work with "with_items"
# This is more verbose, but version safe
- name: install datastax (Redhat)
  yum: name={{datastax}} state=present
  tags:
    - packages 
    - cassandra 
  notify: 
    - restart cassandra
  when: ansible_os_family == "RedHat" 

- name: install cassandra (Redhat)
  yum: name={{cassandra}} state=present
  tags:
    - packages 
    - cassandra 
  notify: 
    - restart cassandra
  when: ansible_os_family == "RedHat" 

########## DEBIAN ########## 

- name: install packages (Debian)
  apt: pkg=wget  state=present
  when: ansible_os_family == "Debian" 
  tags:
    - packages 
    - cassandra 

- name: install packages (Debian)
  apt: pkg=software-properties-common  state=present
  when: ansible_os_family == "Debian" 
  tags:
    - packages 
    - cassandra 

- name: install packages 2 (Debian)
  apt: pkg=python-software-properties  state=present
  when: ansible_os_family == "Debian"
  tags:
    - packages 
    - cassandra 

- name: apt-add-repository (Debian)
  command: apt-add-repository 'deb http://debian.datastax.com/community stable main'
  when: ansible_os_family == "Debian" 
  tags:
    - packages 
    - cassandra 

- name: get datastax repo key (Debian)
  command: wget http://debian.datastax.com/debian/repo_key --output-document=/tmp/datastax.key
  when: ansible_os_family == "Debian"
  tags:
    - packages 
    - cassandra 

- name: add datastax repo key  (Debian)
  command: apt-key add /tmp/datastax.key
  when: ansible_os_family == "Debian"
  tags:
    - packages 
    - cassandra 

- name: install Cassandra (Debian)
  apt: pkg=cassandra=1.2.19 state=present update_cache=yes force=yes
  with_items:
    - $cassandra
  tags:
    - packages 
    - cassandra 
  notify: 
    - restart cassandra
  when: ansible_os_family == "Debian" 

- name: increase stack size (Debian only)
  shell: "sed -e s/Xss180k/Xss256k/g /etc/cassandra/cassandra-env.sh --in-place"
  when: ansible_os_family == "Debian"
  tags:
    - cassandra 

########## BOTH ########## 

- name: setup production settings for Cassandra (not overwrites files)
  copy: src={{item.src}} dest={{item.dest}}
  with_items:
    - { src: conf/90-nproc.conf, dest: /etc/security/limits.d/90-nproc.conf }
    - { src: conf/limits.conf, dest: /etc/security/limits.conf }

- name: create data directory for cassandra on mounted storage
  file: path={{data_dir}}/cassandra state=directory owner={{cassandra_user}}  group={{cassandra_user}}

- name: create the cassandra yaml from template
  template: src=cassandra.yaml dest={{cassandra_yaml}} owner={{cassandra_user}}  group={{cassandra_user}}
  notify: 
    - restart cassandra  





