- debug: msg = "Backing up Postgres database {{ db_name }} on localhost:5432' to {{ backup_dir | default('/data') }}"
  tags:
    - db
    - backup

- shell: "sudo -u {{ db_user }} pg_dump -Fc {{ db_name }} | gzip > {{ db_backup_dir | default('/data') }}/db_`date '+%Y%m%d%H%M%S'`.gz"
  tags:
    - db
    - backup
