- include: ../../common/tasks/setfacts.yml
  tags:
    - biocache-properties
    - biocache-layers    

- name: ensure target directories exist
  file: path={{item}} state=directory
  with_items:
    - "{{data_dir}}/biocache/layers"
    - "{{data_dir}}/biocache/config"    
  tags:
    - biocache-properties    

- name: copy biocache config properties template 
  template: src={{item}} dest={{data_dir}}/biocache/config/{{item}} mode=0644
  with_items:
    - biocache-config.properties
  tags:
    - biocache-properties

- name: Download SDS layers
  get_url: url="http://biocache.ala.org.au/archives/layers/sds-layers.tgz" dest="{{data_dir}}/biocache/layers/sds-layers.tgz" force=yes 
  when: sds_enabled is defined and sds_enabled == true
  tags:
    - biocache-properties
    - biocache-layers    

- name: Extract SDS layers
  shell: "tar zxvf {{data_dir}}/biocache/layers/sds-layers.tgz -C {{data_dir}}/biocache/layers/"
  when: sds_enabled is defined and sds_enabled == true
  tags:
    - biocache-properties
    - biocache-layers    

# - name: set data ownership [all data is owned by tomcat]
#   file: path={{data_dir}}/{{item}} owner={{tomcat_user}} group={{tomcat_user}} recurse=true
#   with_items:
#     - biocache 
#   tags:
#     - biocache-properties
#     - biocache-layers    